M48
; DRILL file {KiCad 9.0.6} date 2026-01-31T12:01:57+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-31T12:01:57+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X123.75Y-139.25
X137.0Y-90.5
X163.5Y-141.5
X168.5Y-90.5
M30
